- Sorting/Selection_sort
> Selection Sort python

- Sorting/Heap Sort
Heap sort is a comparison based sorting technique based on Binary Heap data structure. It is similar to selection sort where we first find the maximum element and place the maximum element at the end. We repeat the same process for the remaining elements.
> Create Heap Sort

- Graphs/kruskals_algorithm.cpp
I have added the kruskals_algorithm to find MST in c++.
> I have added kruskals_algorithm to find MST in cpp

- Matrix Operation/Sum_of_Diagonal.cpp
- Matrix Operation/rotate_image(Anti-clockwise).cpp
- Matrix Operation/rotate_image(Clockwise).cpp
> C++ Solutions for Matrix

- 0-1 Knapsack Problem - DP.cpp
Given weights and values of n items, put these items in a knapsack of capacity W to get the maximum total value in the knapsack. In other words, given two integer arrays val[0..n-1] and wt[0..n-1] which represent values and weights associated with n items respectively. Also given an integer W which represents knapsack capacity, find out the maximum value subset of val[] such that sum of the weights of this subset is smaller than or equal to W. You cannot break an item, either pick the complete item or don’t pick it (0-1 property).
> 0-1 Knapsack Problem -Dynamic Programming

- DoubleHashingC++.txt
- Hash Table Class Chaining.txt
- Hash Table Quadratic Probing.txt
- HashTableLinearProbingC++.txt
> hashing techniques

- Stable_Matching.cpp
Added code for Stable Matching Algorithm.
> Added Stable Matching Algorithm

- Sorting/Randomized_Quick_Sort.cpp
And added explanation too about random partition algorithm.
> Added RandomizedQuickSort

- Number Theory/prime_factors.cpp
- Number Theory/prime_fibonacci.cpp
- Number Theory/prime_generator_between_numbers.cpp
Algo related to number theory.
> Algo related to number theory.

- inversion of an array
> inversion of an array

- longest_commmon_subsequence_of_three_sequences
longest_common_subsequence_of_three_sequrence {cpp}
> longest_common_subsequence_of_three_sequence

- Number Theory/frequency_hashmap.cpp
- Number Theory/kth_smallest_largest.cpp
- Number Theory/nCr.cpp
- Number Theory/nCrModP.cpp
Some more algorithms on number theory.
> Number Theory

- Graphs/Sssp.cpp
- Graphs/bipartite_test.cpp
first is the bipartite test and second is single source shortest path.
> added 2 important  algorithms on graphs

- Sieve_of_Eratosthenes.cpp
I have added the implementation of the popular concept or algorithm known as Sieve of Eratosthenes using c++.
> Sieve Of Eratosthenes

- Sorting/cycle_sort.cpp
cycle sorting was not in the list, so added. 🙏
> cycle sorting

- covering_segments
> covering_segments

- QuickSort.c
Tried to implment Quick Sort in C
> Created QuickSort in C

- Naive Algorithm for Pattern Searching.py
Please Accept for Hacktoberfest
> Create Naive Algorithm for Pattern Searching.py

- Sum of nodes at maximum depth of a Binary Tree.py
> Create Sum of nodes at maximum depth of a Binary Tree.py

- Smooth Sort.py
> Create Smooth Sort.py

- Rabin Karp Algorithm.py
> Create Rabin Karp Algorithm.py

- Shell_Sort.cpp
ShellSort is mainly a variation of Insertion Sort. In insertion sort, we move elements only one position ahead. When an element has to be moved far ahead, many movements are involved. The idea of shellSort is to allow exchange of far items. In shellSort, we make the array h-sorted for a large value of h. We keep reducing the value of h until it becomes 1. An array is said to be h-sorted if all sublists of every h’th element is sorted.
> Shell_Sort.cpp

- PR3/about.html
- PR3/style.css
> Added my third PR

- pr4.py
Added my 4th PR, reverse of an array
> Added my 4th PR

- Convexhull.cpp
this the program for convex hull algorithm
> Convexhull.cpp

- Selection Sort
> Selection_sort.js

- Back-Tracking/sudoku Solver.cpp
I  added the main Logic of Solving Sudoku Solver Problem
> Create Sudoku Solver.cpp

- Graphs/TSP.cpp
Hey there,Please check out my code for Travelling Salesman Problem.
Thank You.
> Travelling Salesman Problem

- starship trooper c++ game.cpp
> Create starship trooper c++ game.cpp

- Lapindrome_in_c++/c++_code_for_checking_Lapindrome
C++ program which checks whether the string is Lapindrome or not
> 'C++_code_for_checking_Lapindrome'

- Number Theory/gcd_of_numbers.cpp
A cpp program to find the gcd of two numbers
> -gcd of two numbers

- Number Theory/matrix_expo.cpp
It is a program to calculate exponentiation of a matrix witout getting TLE.
> Binary Exponentiation

- Amicable Number
Print the number of pairs in the array that form an amicable pair(numbers are amicable if the first is equal to the sum of divisors of the second, and if the second number is equal to the sum of divisors of the first).
> Amicable number

- Python Guessing Game.py
A basic Guessing Game using python 
Keep guessing the computer generated no. and enjoy playing and do comment to let me know your experience playing it.
> Create Python Guessing Game.py

- pointers.cpp
C++ program to demonstrate use of * for pointers in C++ .
> use of * for pointers in C++ .

- Catalan Numbers
This code generates a series of catalan numbers. By @apurvajain10
> Catalan Numbers

- kbc.c
this is the KBC game, the game using a level-up approach just like in the real KBC game.
every time this game produces a new question and the question sequencing is also different
> KBC game using c and randomisation

- infixToPrefix.cpp
This program implements the algorithm used to convert an infix expression (e.g a+b) into a prefix one (+ab).
> added program (in c++) for infix to prefix conversion

- PrintDiamond.cpp
Program added with comments explaining the code
> Added program to print Diamond
